Report, implementation, results
tmplt/ed7039e pull request #46
Opened 2021-01-01 19:13 UTC by Simpen-1

added to the report in the implementation and results part, by simon sandberg and oleksiey michenko

2021-01-02 09:04 UTC, tmplt requested changes
Here is an initial review. Please see to the review comments. Additionally:

* only capitalize the first letter in the first word of each section title to match the style of the report;
* add to `team-members.tex` which member has written which section(s);
* ignore my `\( \)` -> `$$` comments if the compiled result looks like it should (I haven't seen the use of `'\( \)` before);
* finish all captions with a period;
* commit all your figures into `assets/`, and use `\textwidth` instead of a hardcoded width value;
* don't `\newpage` and don't linebreak (`\\`);

Cascade these changes throughout your additions and I'll do a full review.

2021-01-02 09:04 UTC, tmplt commented on report/sections/implementation.tex
> +The robot designated the task of moving the object on the industry platform is built from the Lego Mindstorms EV3 core set package. The design of the robot is based from the \cite{Robot arm} model fr
"The robot designed **for** the task ..."

2021-01-02 09:04 UTC, tmplt commented on report/sections/implementation.tex
> +The docking sequence of the robots movement was implemented using a line follower. A QTRX reflectance sensor from Pololu was used together with a black line to guide the robot close to the factory an
* Describe what the docking sequence is.
* Explain what QTRX means.
* "angle ton the factory(pic)" - what?
* Just call it the "Raspberry Pi".
* Libraries were available to talk to the sensor array, but NixOS was the root cause of the issue here. Blame NixOS itself instead.
* "thru" -> "through"
* Add a reference to the breakout board, like you have done to the EV3 hardware.

2021-01-02 09:04 UTC, tmplt commented on report/sections/implementation.tex
> +The robot designated the task of moving the object on the industry platform is built from the Lego Mindstorms EV3 core set package. The design of the robot is based from the \cite{Robot arm} model fr
Also: use `\parencite` instead.

2021-01-02 09:04 UTC, tmplt commented on report/sections/implementation.tex
> +Adafruit FT232H Breakout is a breakout board from Adafruit which contains the F232H chip from FTDI and has has one port each for a usb c and stemma qt male connectors. The board is also equipped with
* "JTAg" -> "JTAG".
* Remove the trailing "The" or finish the sentence.

2021-01-02 09:04 UTC, tmplt commented on report/sections/implementation.tex
> +\newpage
Remove the `\newpage`. I'll handle the final typesetting before submission.

2021-01-02 09:04 UTC, tmplt commented on report/sections/implementation.tex
> +The Sensor array used in this project was a QTRX-MD-16A Reflectance array from Pololu. Each sensor on the sensor array is made from a photo transistor and paired with an IR-led which powers on and ke
* "led" -> "LED"

2021-01-02 09:04 UTC, tmplt commented on report/sections/implementation.tex
> +    \caption{The Mobile Platform seen from above}
* Commit this image, but move it to `assets/` instead.
* Finish the caption with a period.
* Use `width=\textwidth` instead.

2021-01-02 09:04 UTC, tmplt commented on report/sections/implementation.tex
> +A simplified model of the mobile platform can be seen in figure \ref{Mobile_platform_paint}. The power from each motor is transmitted by a beam to three interconnected gears which in turn are inscirc
* Refer to figures using `Figure~/ref{}` instead.
* "inscircled" -> "encircled".
* "continues" -> "continuous".

2021-01-02 09:04 UTC, tmplt commented on report/sections/implementation.tex
> +    \label{Mobile_platform_paint}
Ditto, and use a different label; the previous one is overwritten now.

2021-01-02 09:04 UTC, tmplt commented on report/sections/implementation.tex
> +In order to get power to each motor servo and the Raspberry PI, two battery packs with 8 batteries in each were used. Since these battery packs together with the Raspberry Pi and the two BrickPi moto
* "Raspberry PI" -> "Raspberry Pi";

2021-01-02 09:04 UTC, tmplt commented on report/sections/implementation.tex
> +    \caption{Arm model side view}
Ditto.

2021-01-02 09:04 UTC, tmplt commented on report/sections/implementation.tex
> +    \caption{Arm model overview}
Ditto.

2021-01-02 09:04 UTC, tmplt commented on report/sections/implementation.tex
> +A simplified model of the robot arm can be seen in figure \ref{Arm_model} where the measured distances from \(d_1\) to \(d_7\) and the vertical angle Theta can be seen. in figure \ref{arm_overview} a
* LaTeX can handle greek letters, so use `\theta` and `\beta` if the same is done in the figures;
* `\(d_1\) to \(d_7\)` -> `$(d_1)$ to $(d_7)$`;
* Fix `in figure \ref{arm_overview}`;

2021-01-02 09:04 UTC, tmplt commented on report/sections/implementation.tex
> +The robot arm can rotate in the xy-plane around the \(z_0\) axis which can be seen in fig. \ref{Arm_model} with a angle Beta using a EV3 large servomotor mounted inside the base of the robot.The uppe
* use `$$` instead of `\( \)`;
* Refer to figures using `Fig~\ref{}` instead;
* use greek letters instead;
* `robot.The upper part of the robot`: sentences are seperated with a space;

2021-01-02 09:04 UTC, tmplt commented on report/sections/implementation.tex
> +There is no memory in the motors which makes the robot "unaware" of the original orientation of the arm on boot. Therefore an initialization process was made for the robot using two Lego EV3 touch se
* quotes in LaTeX are done with 
```
``unare''
```
* don't `\newpage`;

2021-01-02 09:04 UTC, tmplt commented on report/sections/implementation.tex
> +these two expressions both have a denominator which is equal to zero for an angle \(theta = \pm \pi /2\), two angles that the robot can never reach due to the way the Lego hardware is put together.\\
* Don't linebreak (the `\\`)

2021-01-02 09:04 UTC, tmplt commented on report/sections/implementation.tex
> +these two expressions both have a denominator which is equal to zero for an angle \(theta = \pm \pi /2\), two angles that the robot can never reach due to the way the Lego hardware is put together.\\
- use `\frac{\pi}{2}` instead;

2021-01-03 19:09 UTC, Simpen-1 reviewed
done

2021-01-06 17:49 UTC, tmplt approved these changes

2021-01-06 17:50 UTC, merged